import { describe, expect, it } from "vitest";
import { buildConsultantReviewRows, buildLocalDefaultTitle, composeFilename, deriveLocalWorkflowState, extractTemplateFields, knownFieldValue, validateConsultantGeneration } from "./rules.mjs";
import { confirmConsultantReview, startConsultantReview } from "../public/reviewFlow.js";

describe("local consultant LOA generator rules", () => {
  const validInput = { template: "Employment-LOA.docx", projectCode: "INGRASYS", referenceNumber: "LOA-001", reviewConfirmed: true, employee: { signDate: "2026-08-27", fullName: "Veronica Chen", email: "veronica@example.com", nric: "S1234567A", phone: "91234567", jobTitle: "Consultant", salaryType: "Monthly", salaryAmount: "2100", startDate: "2026-09-01", contract: "Fixed-term", employmentPeriod: "6 months", paymentDate: "2026-09-25", remarks: "" }, consultant: { fullName: "Alex Ng", email: "alex@example.com" }, customFields: { department: "Operations" } };

  it("creates a safe local PDF filename", () => { expect(composeFilename("IngrasyS Project", "LOA / 001", "Veronica Chen_Employment Contract")).toBe("IngrasyS-Project_LOA-001_Veronica-Chen-Employment-Contract"); });
  it("discovers Word merge tags from a local template", () => { expect(extractTemplateFields("Hi {{employee_full_name}}, {consultant_email}")).toEqual(["consultant_email", "employee_full_name"]); });
  it("uses the requested editable employee-contract timestamp title default", () => { expect(buildLocalDefaultTitle("Veronica Chen", new Date(2026, 7, 27, 8, 5))).toBe("Veronica Chen_Employment Contract_2026-08-27_08-05"); });
  it("always produces a local signing-ready PDF workflow state", () => { expect(deriveLocalWorkflowState()).toEqual({ folder: "PDF", loaGenerationStatus: "PDF generated", signatureStatus: "Ready for signing" }); });
  it("requires review confirmation and consultant details before generating", () => { expect(validateConsultantGeneration({ ...validInput, reviewConfirmed: false, consultant: { fullName: "", email: "" } }, [])).toEqual(["Review the LOA details before generating the PDF.", "Enter the consultant’s full name.", "Enter the consultant’s email."]); });
  it("requires unknown fields from the chosen template and maps standard values", () => { expect(validateConsultantGeneration(validInput, ["department"])).toEqual([]); expect(knownFieldValue("nric", validInput)).toBe("S1234567A"); expect(knownFieldValue("consultant_email", validInput)).toBe("alex@example.com"); });
  it("builds the employee, consultant, and selected-template details for review", () => { const rows = buildConsultantReviewRows(validInput); expect(rows).toContainEqual(["Employee full name", "Veronica Chen"]); expect(rows).toContainEqual(["Consultant email", "alex@example.com"]); expect(rows).toContainEqual(["department", "Operations"]); });
  it("moves a local consultant form through review before the PDF-generation request", () => { const reviewing = startConsultantReview(validInput); expect(reviewing).toMatchObject({ stage: "review", payload: { reviewConfirmed: false } }); const confirmed = confirmConsultantReview(reviewing); expect(confirmed).toMatchObject({ stage: "generating", payload: { reviewConfirmed: true } }); });
});
