import DashboardLayout from "@/components/DashboardLayout";
import { Button } from "@/components/ui/button";
import { useAuth } from "@/_core/hooks/useAuth";
import { trpc } from "@/lib/trpc";
import { ShieldCheck, UserRoundCheck, UsersRound } from "lucide-react";

export default function Admin() {
  const { user } = useAuth();
  const utils = trpc.useUtils();
  const { data: members, isLoading, error } = trpc.workspace.members.useQuery(undefined, { enabled: user?.role === "admin" });
  const updateRole = trpc.workspace.setMemberRole.useMutation({ onSuccess: () => utils.workspace.members.invalidate() });
  return <DashboardLayout><section className="mx-auto max-w-5xl"><p className="text-xs font-semibold uppercase tracking-[0.16em] text-[#5f7f68]">Administration</p><h1 className="mt-2 font-serif text-4xl tracking-tight text-[#193d37]">Access & roles</h1><p className="mt-3 max-w-3xl text-sm leading-6 text-[#6e7b73]">Colleagues become available here after their first secure sign-in. Administrators can authorize document creators and grant additional administration access.</p>{user?.role !== "admin" ? <div className="mt-8 rounded-2xl border border-[#f0d6cf] bg-[#fff7f5] p-6 text-sm text-[#8b4a3f]">Administrator access is required to manage roles.</div> : <div className="mt-8 overflow-hidden rounded-2xl border border-[#e0e6df] bg-white shadow-[0_12px_40px_rgba(25,61,55,0.05)]"><div className="flex items-start gap-3 border-b border-[#edf0ec] px-6 py-5"><span className="flex h-9 w-9 items-center justify-center rounded-xl bg-[#edf5ee] text-[#2f6a55]"><UsersRound className="h-4 w-4" /></span><div><h2 className="font-serif text-xl font-semibold text-[#193d37]">Authorized workspace members</h2><p className="mt-1 text-xs text-[#77827e]">There is no external directory synchronization in this initial release; members appear after authenticating once.</p></div></div>{isLoading ? <p className="p-6 text-sm text-[#77827e]">Loading members…</p> : error ? <p className="p-6 text-sm text-[#9b4037]">{error.message}</p> : <div className="divide-y divide-[#edf0ec]">{members?.map(member => <div key={member.id} className="flex flex-col gap-3 px-6 py-5 sm:flex-row sm:items-center"><span className="flex h-9 w-9 items-center justify-center rounded-xl bg-[#f0f4ef] text-[#4b705d]"><UserRoundCheck className="h-4 w-4" /></span><div className="min-w-0 flex-1"><p className="truncate font-medium text-[#294036]">{member.name || "Unnamed colleague"}</p><p className="truncate text-xs text-[#77827e]">{member.email || "No email available"} · Last sign-in {new Date(member.lastSignedIn).toLocaleDateString()}</p></div><div className="flex items-center gap-2"><span className={`rounded-full px-2.5 py-1 text-[11px] font-semibold ${member.role === "admin" ? "bg-[#e8f2e9] text-[#2f6a55]" : "bg-stone-100 text-stone-600"}`}>{member.role === "admin" ? "Administrator" : "Authorized creator"}</span>{member.id !== user.id ? <Button size="sm" variant="outline" disabled={updateRole.isPending} onClick={() => updateRole.mutate({ userId: member.id, role: member.role === "admin" ? "user" : "admin" })}>{member.role === "admin" ? "Make creator" : "Make admin"}</Button> : <span className="inline-flex items-center gap-1 text-xs font-medium text-[#557060]"><ShieldCheck className="h-3.5 w-3.5" />You</span>}</div></div>)}</div>}</div>}</section></DashboardLayout>;
}
