import DashboardLayout from "@/components/DashboardLayout";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { trpc } from "@/lib/trpc";
import { CheckCircle2, FileUp, FolderPlus, Plus, Settings2 } from "lucide-react";
import { ChangeEvent, FormEvent, useMemo, useState } from "react";

function normalizeFieldKey(value: string) {
  const withoutBraces = value.trim().replace(/^\{+\s*|\s*\}+$/g, "");
  const withBoundaries = withoutBraces.replace(/([a-z0-9])([A-Z])/g, "$1_$2");
  const normalized = withBoundaries.toLowerCase().replace(/[^a-z0-9]+/g, "_").replace(/^_+|_+$/g, "");
  return normalized ? (/^[a-z]/.test(normalized) ? normalized : `field_${normalized}`).slice(0, 80) : "";
}

async function toBase64(file: File) {
  return new Promise<string>((resolve, reject) => {
    const reader = new FileReader();
    reader.onload = () => resolve(String(reader.result).split(",")[1] || "");
    reader.onerror = () => reject(new Error("File could not be read."));
    reader.readAsDataURL(file);
  });
}

export default function Templates() {
  const utils = trpc.useUtils();
  const { data, isLoading } = trpc.workspace.overview.useQuery();
  const [projectName, setProjectName] = useState(""); const [projectCode, setProjectCode] = useState("");
  const [templateName, setTemplateName] = useState(""); const [templateProject, setTemplateProject] = useState("");
  const [fieldTemplate, setFieldTemplate] = useState(""); const [fieldLabel, setFieldLabel] = useState(""); const [fieldKey, setFieldKey] = useState(""); const [fieldScope, setFieldScope] = useState<"shared" | "project">("project"); const [required, setRequired] = useState(true);
  const [uploadTemplate, setUploadTemplate] = useState(""); const [uploadVersion, setUploadVersion] = useState(""); const [file, setFile] = useState<File | null>(null); const [message, setMessage] = useState("");
  const normalizedFieldKey = useMemo(() => normalizeFieldKey(fieldKey || fieldLabel), [fieldKey, fieldLabel]);
  const refresh = async (text: string) => { setMessage(text); await utils.workspace.overview.invalidate(); };
  const projectMutation = trpc.projects.create.useMutation({ onSuccess: () => refresh("Project created."), onError: error => setMessage(error.message) });
  const templateMutation = trpc.templates.create.useMutation({ onSuccess: () => refresh("Template created. Map fields and upload its approved DOCX version next."), onError: error => setMessage(error.message) });
  const fieldMutation = trpc.templates.addField.useMutation({ onSuccess: () => { setFieldKey(normalizedFieldKey); refresh(`Document field added as {{${normalizedFieldKey}}}. Use that exact merge tag in the DOCX template.`); }, onError: error => setMessage(error.message) });
  const uploadMutation = trpc.templates.uploadVersion.useMutation({ onSuccess: () => refresh("DOCX version uploaded as a draft. Approve it when ready."), onError: error => setMessage(error.message) });
  const approveMutation = trpc.templates.approveVersion.useMutation({ onSuccess: () => refresh("Template version approved for LOA generation."), onError: error => setMessage(error.message) });
  const projects = data?.projects ?? []; const templates = data?.templates ?? []; const versions = data?.templateVersions ?? []; const fields = data?.templateFields ?? [];
  async function upload(event: FormEvent) { event.preventDefault(); if (!file || !uploadTemplate || !uploadVersion) return setMessage("Select a template, version, and DOCX file."); try { await uploadMutation.mutateAsync({ templateId: uploadTemplate, version: uploadVersion, filename: file.name, documentBase64: await toBase64(file) }); } catch (cause) { setMessage(cause instanceof Error ? cause.message : "Upload failed."); } }
  function addField(event: FormEvent) { event.preventDefault(); if (!normalizedFieldKey) return setMessage("Enter a field label or merge tag."); fieldMutation.mutate({ templateId: fieldTemplate, label: fieldLabel || normalizedFieldKey.replaceAll("_", " "), fieldKey: normalizedFieldKey, fieldScope, isRequired: required, position: fields.filter(field => field.templateId === fieldTemplate).length + 1 }); }
  return <DashboardLayout><section className="mx-auto max-w-6xl"><p className="text-xs font-semibold uppercase tracking-[0.16em] text-[#5f7f68]">Configuration</p><h1 className="mt-2 font-serif text-4xl tracking-tight text-[#193d37]">Approved template library</h1><p className="mt-3 max-w-3xl text-sm leading-6 text-[#6e7b73]">Each LOA is generated from a controlled DOCX version. Configure the project, define merge fields, and approve the exact version allowed to generate documents.</p>{message ? <p className="mt-5 rounded-xl bg-[#eaf4ec] px-4 py-3 text-sm text-[#2d654a]">{message}</p> : null}
    <div className="mt-8 grid gap-6 lg:grid-cols-2"><Panel icon={FolderPlus} title="1. Add a project" detail="Create one configuration for each LOA variant or future project."><form className="grid gap-3" onSubmit={event => { event.preventDefault(); projectMutation.mutate({ name: projectName, code: projectCode }); }}><Input value={projectName} onChange={event => setProjectName(event.target.value)} placeholder="Project name" required /><Input value={projectCode} onChange={event => setProjectCode(event.target.value)} placeholder="Project code, e.g. ALPHA" required /><Button disabled={projectMutation.isPending} className="justify-self-start bg-[#193d37] hover:bg-[#0f2c27]"><Plus className="mr-2 h-4 w-4" />Add project</Button></form></Panel>
      <Panel icon={Settings2} title="2. Add a template" detail="A project can have one or more controlled LOA templates."><form className="grid gap-3" onSubmit={event => { event.preventDefault(); templateMutation.mutate({ projectId: templateProject, name: templateName }); }}><Select value={templateProject} onChange={setTemplateProject} placeholder="Select project" options={projects.map(project => ({ value: project.id, label: `${project.code} · ${project.name}` }))} /><Input value={templateName} onChange={event => setTemplateName(event.target.value)} placeholder="Template name" required /><Button disabled={templateMutation.isPending || !projects.length} className="justify-self-start bg-[#193d37] hover:bg-[#0f2c27]"><Plus className="mr-2 h-4 w-4" />Add template</Button></form></Panel>
      <Panel icon={Plus} title="3. Map document fields" detail="Paste a field label or a Word merge tag. The generator safely converts it to a snake-case tag, e.g. {{Candidate Full Name}} becomes {{candidate_full_name}}."><form className="grid gap-3" onSubmit={addField}><Select value={fieldTemplate} onChange={setFieldTemplate} placeholder="Select template" options={templates.map(template => ({ value: template.id, label: template.name }))} /><Input value={fieldLabel} onChange={event => setFieldLabel(event.target.value)} placeholder="Field label, e.g. Candidate full name" /><Input value={fieldKey} onChange={event => setFieldKey(event.target.value)} onBlur={() => setFieldKey(normalizedFieldKey)} placeholder="Merge field or tag, e.g. {{candidate_full_name}}" required /><p className="-mt-1 text-xs text-[#6d7d73]">Stored merge tag: <code className="rounded bg-[#edf3ee] px-1.5 py-0.5 text-[#315743]">{normalizedFieldKey ? `{{${normalizedFieldKey}}}` : "Enter a label or field name"}</code></p><select className="h-10 rounded-md border border-input bg-background px-3 text-sm" value={fieldScope} onChange={event => setFieldScope(event.target.value as "shared" | "project")}><option value="project">Project-specific field</option><option value="shared">Shared field</option></select><label className="flex items-center gap-2 text-sm text-[#4d5f55]"><input type="checkbox" checked={required} onChange={event => setRequired(event.target.checked)} />Required before review</label><Button disabled={fieldMutation.isPending || !templates.length} className="justify-self-start bg-[#193d37] hover:bg-[#0f2c27]"><Plus className="mr-2 h-4 w-4" />Add field</Button></form></Panel>
      <Panel icon={FileUp} title="4. Upload & approve DOCX" detail="Only one version per template is approved at any time. Keep original layout in the source template."><form className="grid gap-3" onSubmit={upload}><Select value={uploadTemplate} onChange={setUploadTemplate} placeholder="Select template" options={templates.map(template => ({ value: template.id, label: template.name }))} /><Input value={uploadVersion} onChange={event => setUploadVersion(event.target.value)} placeholder="Version, e.g. 1.0" required /><Input type="file" accept=".docx,application/vnd.openxmlformats-officedocument.wordprocessingml.document" onChange={(event: ChangeEvent<HTMLInputElement>) => setFile(event.target.files?.[0] || null)} required /><Button type="submit" disabled={uploadMutation.isPending || !templates.length} className="justify-self-start bg-[#193d37] hover:bg-[#0f2c27]">{uploadMutation.isPending ? "Uploading…" : "Upload draft version"}</Button></form></Panel></div>
    <div className="mt-8 overflow-hidden rounded-2xl border border-[#e0e6df] bg-white"><div className="border-b border-[#edf0ec] px-6 py-5"><h2 className="font-serif text-2xl font-semibold text-[#193d37]">Configured templates</h2></div>{isLoading ? <p className="p-6 text-sm text-[#748078]">Loading template library…</p> : templates.length === 0 ? <p className="p-8 text-sm text-[#748078]">No templates configured. Begin by adding your first project.</p> : <div className="divide-y divide-[#edf0ec]">{templates.map(template => { const project = projects.find(item => item.id === template.projectId); const templateVersions = versions.filter(version => version.templateId === template.id); const templateFields = fields.filter(field => field.templateId === template.id); return <div key={template.id} className="px-6 py-5"><div className="flex flex-col gap-4 md:flex-row md:items-center"><div className="min-w-0 flex-1"><p className="font-medium text-[#233a33]">{template.name}</p><p className="mt-1 text-xs text-[#78837c]">{project?.code || "Project"} · {templateFields.length} mapped field{templateFields.length === 1 ? "" : "s"}</p></div><div className="flex flex-wrap gap-2">{templateVersions.length === 0 ? <span className="rounded-full bg-[#fbf3dd] px-2.5 py-1 text-[11px] font-semibold text-[#806116]">No version uploaded</span> : templateVersions.map(version => <span key={version.id} className="inline-flex items-center gap-2 rounded-full border border-[#dfe6df] px-2.5 py-1 text-[11px] font-semibold text-[#617169]">v{version.version} · {version.status}{version.status !== "approved" ? <button onClick={() => approveMutation.mutate({ versionId: version.id })} className="text-[#286148] underline underline-offset-2">Approve</button> : <CheckCircle2 className="h-3.5 w-3.5 text-[#3c7b59]" />}</span>)}</div></div>{templateFields.length ? <p className="mt-3 text-xs text-[#77827b]">Fields: {templateFields.map(field => `${field.fieldScope === "shared" ? "Shared" : "Project"} · {{${field.fieldKey}}}`).join(" · ")}</p> : null}</div>; })}</div>}</div></section></DashboardLayout>;
}

function Select({ value, onChange, placeholder, options }: { value: string; onChange: (value: string) => void; placeholder: string; options: { value: string; label: string }[] }) { return <select className="h-10 rounded-md border border-input bg-background px-3 text-sm" value={value} onChange={event => onChange(event.target.value)} required><option value="">{placeholder}</option>{options.map(option => <option key={option.value} value={option.value}>{option.label}</option>)}</select>; }
function Panel({ icon: Icon, title, detail, children }: { icon: typeof FolderPlus; title: string; detail: string; children: React.ReactNode }) { return <div className="rounded-2xl border border-[#e0e6df] bg-white p-6 shadow-[0_12px_40px_rgba(25,61,55,0.04)]"><span className="flex h-9 w-9 items-center justify-center rounded-xl bg-[#edf5ee] text-[#2f6a55]"><Icon className="h-4 w-4" /></span><h2 className="mt-4 font-serif text-xl font-semibold text-[#193d37]">{title}</h2><p className="mt-1 min-h-10 text-xs leading-5 text-[#748078]">{detail}</p><div className="mt-5">{children}</div></div>; }
